packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.28.1
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@eslint-react/eslint-plugin': ^1.38.0
  '@playwright/test': ^1.51.1
  '@rsbuild/core': ~1.2.19
  '@rsbuild/plugin-react': ^1.1.1
  '@rslib/core': ^0.5.5
  '@rspress/plugin-playground': ^1.43.9
  '@rspress/plugin-preview': ^1.43.9
  '@rspress/plugin-typedoc': ^1.43.9
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.2.0
  '@types/node': ^22.13.10
  '@types/react': ^18.3.13
  '@types/react-dom': ^18.3.1
  '@visactor/react-vchart': ^1.13.8
  '@visactor/vchart': ^1.13.8
  '@visactor/vchart-theme-utils': ^1.12.2
  '@visactor/vutils': ^0.19.4
  dayjs: ^1.11.13
  eslint: ^9.23.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  lint-staged: ^15.5.0
  nx: ^20.6.4
  playwright: ^1.51.1
  react: ^18.3.1
  react-dom: ^18.3.1
  rspress: ^1.43.9
  simple-git-hooks: ^2.12.1
  typescript: ^5.8.2
  vitest: ^3.0.9
