packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.8.1
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.28.1
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@eslint-react/eslint-plugin': ^1.31.0
  '@rsbuild/core': ~1.2.13
  '@rsbuild/plugin-react': ^1.1.1
  '@rslib/core': ^0.5.4
  '@rspress/plugin-last-updated': ^1.43.2
  '@rspress/plugin-playground': ^1.43.2
  '@rspress/plugin-preview': ^1.43.2
  '@rspress/plugin-typedoc': ^1.43.2
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.2.0
  '@types/node': ^22.13.10
  '@types/react': ^18.3.13
  '@types/react-dom': ^18.3.1
  '@visactor/react-vchart': ^1.13.6
  '@visactor/vchart': ^1.13.6
  '@visactor/vutils': ^0.19.4
  '@visactor/vchart-theme-utils': ^1.12.2
  dayjs: ^1.11.13
  simple-git-hooks: ^2.11.1
  eslint: ^9.21.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  lint-staged: ^15.4.3
  react: ^18.3.1
  react-dom: ^18.3.1
  rspress: ^1.40.2
  typescript: ^5.8.2
  vitest: ^3.0.7
