packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.29.0
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@eslint-react/eslint-plugin': ^1.47.2
  '@playwright/test': ^1.51.1
  '@rcuse/core': ^0.25.0
  '@rsbuild/core': ^1.3.22
  '@rsbuild/plugin-react': ^1.3.2
  '@rslib/core': ^0.10.0
  '@rspress/plugin-playground': ^1.44.0
  '@rspress/plugin-preview': ^1.44.0
  '@rspress/plugin-typedoc': ^1.44.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@types/node': ^22.13.10
  '@types/react': ^18.3.13
  '@types/react-dom': ^18.3.1
  '@visactor/react-vchart': 2.0.0
  '@visactor/vchart': 2.0.0
  '@visactor/vutils': 1.0.6
  dayjs: ^1.11.13
  es-toolkit: ^1.38.0
  eslint: ^9.24.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  lint-staged: ^15.5.1
  nx: ^20.7.2
  playwright: ^1.51.1
  react: ^18.3.1
  react-dom: ^18.3.1
  rspress: ^1.44.0
  simple-git-hooks: ^2.12.1
  typescript: ^5.8.2
  vitest: ^3.1.1
