export const data1 = [
  { date: 0, value: 0 },
  { date: 1, value: 0 },
  { date: 2, value: 0 },
  { date: 3, value: 0 },
  { date: 4, value: 0 },
  { date: 5, value: 0 },
  { date: 6, value: 0 },
  { date: 7, value: 0 },
  { date: 8, value: 0 },
  { date: 9, value: 0 },
  { date: 10, value: 0 },
  { date: 11, value: 0 },
  { date: 12, value: 0 },
  { date: 13, value: 1 },
  { date: 14, value: 0 },
  { date: 15, value: 0 },
  { date: 16, value: 0 },
  { date: 17, value: 0 },
  { date: 18, value: 0 },
  { date: 19, value: 0 },
  { date: 20, value: 0 },
  { date: 21, value: 0 },
  { date: 22, value: 0 },
  { date: 23, value: 0 },
];
